skillMetadata:
  sections:
    - name: Options << Name of section
      fields:
        - name: placeholder
          type: text
          label: Placeholder
          value: ""
          placeholder: This space for rent
