skillMetadata:
  sections:
    - name: Meal Plan Settings
      fields:
        - name: meals
          type: text
          label: Meals
          value: "Spaghetti and meatballs,Toasted sandwiches and tomato soup,Chicken noodle soup,Peanut butter and jelly sandwiches"
          placeholder: Comma-separated list of meals
