name: Auto translate
on:
  workflow_dispatch:

jobs:
  autotranslate:
    uses: openvoiceos/.github/.github/workflows/auto_translate.yml@feat/shared_actions1
    with:
      branch: ${{ github.event.inputs.branch }}
      action_branch: feat/shared_actions1
      python_version: "3.10"
      locale_folder: locale
